### ISSUE TITLE
Unsoundness in `DataBuffer::push`

### ISSUE THREAD

**Issue by shinmao** [elrnv/buffer#2]
### The source of unsoundness
```rs
pub fn push<T: Any>(&mut self, element: T) -> Option<&mut Self> {
        self.check_ref::<T>()?;
        let element_ref = &element;
        let element_byte_ptr = element_ref as *const T as *const u8;
        let element_byte_slice = unsafe { slice::from_raw_parts(element_byte_ptr, size_of::<T>()) };
        unsafe { self.push_bytes(element_byte_slice) }
    }
```
https://docs.rs/data-buffer/0.8.0/src/data_buffer/lib.rs.html#248-254
There are two unsoundness in the `from_slice` method. First of all, allocator and deallocator got different alignment on vector, which will lead to undefined behavior. Secondly, the code will call `from_raw_parts` to create a slice starting from raw pointer to `u8`. Based on the [doc of slice::from_raw_parts](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html):
> data must be [valid](https://doc.rust-lang.org/std/ptr/index.html#safety) for reads for len * mem::size_of::<T>() many bytes, and it must be properly aligned.

If caller of `push` passes a byte containing padding bytes as `T`, it can lead to uninitialized memory exposure because the slice is returned to caller.

### To reproduce the bug
```rs
use data_buffer::DataBuffer;
use std::mem::align_of;

#[derive(Copy, Clone, Debug)]
pub struct A {
    a: i8,
    b: i32,
    c: i8,
}


fn main() {
    let sa = A { a: 10, b: 11, c: 12 };
    println!("align: {}", align_of::<A>());
    let struct_arr: [A; 10] = [sa; 10];
    let mut buf = DataBuffer::from_slice(&struct_arr);
    println!("{:?}", buf.push(sa));
}
```
Run with Miri,
```
error: Undefined Behavior: incorrect layout on deallocation: alloc2486 has size 80 and alignment 4, but gave size 80 and alignment 1
```
I also summarized backtrace information to help debug here (start from top to bottom here)
```
data_buffer::DataBuffer::push::<A>
data_buffer::DataBuffer::push_bytes
std::vec::Vec::<u8>::extend_from_slice
<std::vec::Vec<u8> as std::vec::spec_extend::SpecExtend<&u8, std::slice::Iter<'_, u8>>>::spec_extend
std::vec::Vec::<u8>::append_elements
std::vec::Vec::<u8>::reserve
alloc::raw_vec::RawVec::<u8>::reserve
alloc::raw_vec::RawVec::<T, A>::reserve::do_reserve_and_handle::<u8, std::alloc::Global>
alloc::raw_vec::RawVec::<u8>::grow_amortized
alloc::raw_vec::finish_grow::<std::alloc::Global>
<std::alloc::Global as std::alloc::Allocator>::grow
std::alloc::Global::grow_impl
std::alloc::realloc
```

**Comment by elrnv** [comment]
Hi @shinmao, thank you very much for this issue and for the detailed report. I have not looked at this crate in a while, but if I remember correctly, the implementation does not respect allocation alignment. I have no intention of fixing issues in this crate at this time since it was replaced with a more feature-full and memory-safe [dync](https://github.com/elrnv/dync.git] crate, which I still maintain.
